var $list1=$('#list1').attr('background-color');
$('#list1').click(function(){
	$(this).css("background-color","rgb(0, 0, 40)");
    $('#titlelist').css("color","white");
    $('#list2').css("background-color","white");
    $('#piclist').css("color","rgb(0, 0, 40)");
    $('#table1').css('display','table');
    $('#table2').css('display','none');
    $('#page').css('float','none');
    $('#page').css('width','100%');
    $('#search').css('float','none');
    $('#board').css('float','none');
    $('#board').css('border-top','solid 50px rgba(220, 220, 220, 0.3)');
    $('#board').css('border-left','solid 10px rgba(220, 220, 220, 0.3)');
    $('#board').css('border-right','solid 10px rgba(220, 220, 220, 0.3)');
    $('#board').css('border-bottom','solid 30px rgba(220, 220, 220, 0.3)');
});
$('#list2').click(function(){
	$(this).css("background-color","rgb(0, 0, 40)");
    $('#piclist').css("color","white");
    $('#list1').css("background-color","white");
    $('#titlelist').css("color","rgb(0, 0, 40)");
    $('#table1').css('display','none');
    $('#table2').css('display','block');
    $('#page').css('float','left');
    $('#page').css('width','100%');
    $('#search').css('float','left');
    $('#board').css('float','left');
    $('#board').css('border','none');
});